name: CS102 Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pylint pytest-cov
        pip install -r homework06/requirements.txt
    - name: Run pytest
      run: |
        pytest ${{ github.head_ref }}
    - name: Run pylint
      run: |
        pylint --exit-zero ${{ github.head_ref }}
    - name: Run mypy
      run: |
        mypy ${{ github.head_ref }} --ignore-missing --strict --exclude "tests"
    - name: Run black
      run: |
        black --exclude "test*" ${{ github.head_ref }} -l 100
